src/Entity/Journalist.php
<?php

namespace App\Entity;

use App\Repository\JournalistRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: JournalistRepository::class)]
class Journalist
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $email = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $bio = null;

    #[ORM\ManyToMany(targetEntity: Article::class, mappedBy: 'journalists')]
    private Collection $articles;

    #[ORM\Column(nullable: true)]
    private ?bool $isGeneric = null;

    public function __construct()
    {
        $this->articles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getBio(): ?string
    {
        return $this->bio;
    }

    public function setBio(?string $bio): self
    {
        $this->bio = $bio;

        return $this;
    }

    /**
     * @return Collection<int, Article>
     */
    public function getArticles(): Collection
    {
        $iterator = $this->articles->getIterator();
        $iterator->uasort(function (Article $a, Article $b) {
            return $a->getDate() <=> $b->getDate();
        });
        return $this->articles;
    }

    public function addArticle(Article $article): self
    {
        if (!$this->articles->contains($article)) {
            $this->articles->add($article);
            $article->addJournalist($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): self
    {
        if ($this->articles->removeElement($article)) {
            $article->removeJournalist($this);
        }

        return $this;
    }

    public function getAllNewspapers(): array
    {
        $newspapers = [];
        foreach ($this->getArticles() as $article) {
            $newspapers = array_merge($newspapers, $article->getNewspapers()->toArray());
        }
        return $newspapers;
    }

    public function isIsGeneric(): ?bool
    {
        return $this->isGeneric;
    }

    public function setIsGeneric(?bool $isGeneric): self
    {
        $this->isGeneric = $isGeneric;

        return $this;
    }
}

src/Controller/JournalistController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;

use App\Entity\Journalist;
use App\Entity\Newspaper;
use Symfony\Component\HttpFoundation\Request;

class JournalistController extends AbstractController
{

    private $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    #[Route('/journalist', name: 'app_journalist')]
    public function index(): Response
    {
        // Get all the journalists from the database
        $journalists = $this->entityManager->getRepository(Journalist::class)->findBy([], ['name' => 'ASC']);

        // Render the journalist page
        return $this->render('journalist/index.html.twig', [
            'journalists' => $journalists,
        ]);
    }

    #[Route('/journalist/{id}', name: 'app_journalist_show')]
    public function show(int $id): Response
    {
        // Get the journalist from the database
        $journalist = $this->entityManager->getRepository(Journalist::class)->find($id);

        // get all newspapers from the journalist
        $newspapers = $this->entityManager->getRepository(Newspaper::class)->getAllNewspapersFromJournalist($id);

        // Render the journalist page
        return $this->render('journalist/show.html.twig', [
            'journalist' => $journalist,
            'newspapers' => $newspapers,
        ]);
    }

    #[Route('/journalist/{id}/mark', name: 'app_journalist_mark_as_generic')]
    public function markAsGeneric(int $id, Request $request): Response
    {
        // Get the journalist from the database
        $journalist = $this->entityManager->getRepository(Journalist::class)->find($id);

        // Mark the journalist as generic
        $journalist->setIsGeneric(true);

        // Save the changes to the database
        $this->entityManager->flush();

        // Get the URL of the referring page
        $referer = $request->headers->get('referer');

        // Redirect back to the referring page
        return $this->redirect($referer);
    }

    #[Route('/journalist/{id}/unmark', name: 'app_journalist_mark_as_not_generic')]
    public function markAsNotGeneric(int $id, Request $request): Response
    {
        // Get the journalist from the database
        $journalist = $this->entityManager->getRepository(Journalist::class)->find($id);

        // Mark the journalist as not generic
        $journalist->setIsGeneric(false);

        // Save the changes to the database
        $this->entityManager->flush();

        // Get the URL of the referring page
        $referer = $request->headers->get('referer');

        // Redirect back to the referring page
        return $this->redirect($referer);
    }
}

templates/journalist/_list.html.twig
<table>
	<thead>
		<tr>
			<th>Journalists</th>
			<th>NPs</th>
		</tr>
	</thead>
	<tbody>
		{% for journalist in journalists %}
			<tr>
				<td>
					{% include 'journalist/_single.html.twig' with { 'journalist': journalist } %}
				</td>
				<td>
					{% set grouped_newspapers = journalist.allNewspapers|group_by('name') %}
					{% for newspaper, duplicates in grouped_newspapers %}
						{% include 'newspaper/_tag.html.twig' with { 'newspaper': duplicates[0] } %}
						{% if duplicates|length > 1 %}
							(+
							{{ duplicates|length - 1 }})
						{% endif %}
					{% endfor %}
				</td>
			</tr>
		</td>
	</tbody>
</tr>{% endfor %}</tbody></table>

templates/journalist/_single.html.twig
{% if app.user %}
	<div class="meta-actions">
		<a href="{{ path('app_journalist_show', { 'id': journalist.id }) }}">{{ journalist.name }}</a>
		<div class="actions">
			{% if not journalist.isGeneric %}
				<a href="{{ path('app_journalist_mark_as_generic', { 'id': journalist.id }) }}">📰</a>
			{% else %}
				<a href="{{ path('app_journalist_mark_as_not_generic', { 'id': journalist.id }) }}">👩‍💻</a>
			{% endif %}
		</div>
	</div>
{% else %}
	<a href="{{ path('app_journalist_show', { 'id': journalist.id }) }}">{{ journalist.name }}
		test</a>
{% endif %}

{% block stylesheets %}
	<style>
		.meta-actions:hover .actions {
			display: inline;
		}

		.actions {
			display: none;
		}
	</style>
{% endblock %}

templates/journalist/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ArticleController!{% endblock %}

{% block body %}
    <div class="example-wrapper">
    <h1>✍️ Journalists</h1>

    <p>Now we iterate over each journalist and display its name:</p>
    {% include 'journalist/_list.html.twig' with {'journalists': journalists} %}
</div>

{% endblock %}

templates/journalist/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ArticleController!
{% endblock %}

{% block body %}
	<h2>{{ journalist.name }}
		{% if journalist.isGeneric %}
			(Generic)
		{% endif %}
	</h2>

	<p>{{ journalist.name }}
		has written
		{{ journalist.articles|length }}
		article
		{% if journalist.articles|length > 1 %}s
		{% endif %}:</p>
	{%include 'article/_list.html.twig' with {'articles': journalist.articles} %}
	{% if newspapers|length == 0 %}
		<p>Journalist
			{{ journalist.name }}
			has not written for any newspapers</p>
	{% else %}
		<p>Journalist
			{{ journalist.name }}
			has written for
			{{ newspapers|length }}
			newspaper
			{% if newspapers|length > 1 %}s
			{% endif %}:</p>
		{%include 'newspaper/_list.html.twig' with {'newspapers': newspapers} %}
	{% endif %}


	<p>Go back to articles
		<a href="{{ path('app_article') }}">here</a>
	</p>

{% endblock %}